// Generated by scripts/sync-content-locales.mjs from i18n/content. Do not edit by hand.
export const focusedGuideMeta = {
  'google-authenticator-web': {
    en: {
      title: 'Google Authenticator on a computer',
      description:
        'Google Authenticator has no official web or PC version. Learn how to get the same codes on a computer from your setup key or export QR, and the trade-offs.',
      sources: [
        {
          title: 'Google: Get verification codes with Google Authenticator',
          url: 'https://support.google.com/accounts/answer/1066447?hl=en'
        },
        {
          title: 'RFC 6238: the TOTP algorithm',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: '2fa.hot project information and supported features',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        }
      ]
    },
    'zh-CN': {
      title: '谷歌身份验证器网页版',
      description:
        '谷歌身份验证器（Google Authenticator）没有官方网页版或电脑版。本文介绍如何用已保存的密钥或导出二维码在电脑上获取相同验证码，以及相应的安全取舍。',
      sources: [
        {
          title: 'Google：通过 Google 身份验证器获取验证码',
          url: 'https://support.google.com/accounts/answer/1066447?hl=en'
        },
        {
          title: 'RFC 6238：TOTP 算法说明',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: '2fa.hot 项目介绍与支持功能',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        }
      ]
    },
    'zh-TW': {
      title: 'Google Authenticator 網頁版',
      description:
        'Google Authenticator 沒有官方網頁版或電腦版。本文說明如何用已保存的金鑰或匯出的 QR Code 在電腦上取得相同驗證碼，以及需要留意的安全取捨。',
      sources: [
        {
          title: 'Google：透過 Google Authenticator 取得驗證碼',
          url: 'https://support.google.com/accounts/answer/1066447?hl=en'
        },
        {
          title: 'RFC 6238：TOTP 演算法說明',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: '2fa.hot 專案介紹與支援功能',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        }
      ]
    },
    ja: {
      title: 'Google AuthenticatorをPCで使う',
      description:
        'Google Authenticatorに公式のWeb版・PC版はありません。シークレットキーやエクスポートQRを使ってPCで同じコードを表示する方法と注意点を解説します。',
      sources: [
        {
          title: 'Google：Google 認証システムで確認コードを取得する',
          url: 'https://support.google.com/accounts/answer/1066447?hl=en'
        },
        {
          title: 'RFC 6238：TOTPアルゴリズム',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: '2fa.hotのプロジェクト情報と対応機能',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        }
      ]
    }
  },
  'find-2fa-secret-key': {
    en: {
      title: 'Where to find your 2FA secret key',
      description:
        'What a 2FA secret key looks like, where services show it during authenticator setup, how to get a new one if you did not save it, and how to store it safely.',
      sources: [
        {
          title: 'GitHub Docs: Configuring two-factor authentication',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'GitHub Docs: Changing your two-factor authentication method',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-two-factor-authentication-delivery-methods-for-your-mobile-device'
        },
        {
          title: 'RFC 4648: the Base32 alphabet',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        }
      ]
    },
    'zh-CN': {
      title: '2FA 密钥在哪里找',
      description:
        '2FA 密钥是什么、长什么样？了解设置验证器时在哪里找到密钥，没保存时如何重新获取，以及如何安全保存、为什么不能随意发给别人。',
      sources: [
        {
          title: 'GitHub 文档：配置双重身份验证',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'GitHub 文档：更改双重身份验证方法',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-two-factor-authentication-delivery-methods-for-your-mobile-device'
        },
        {
          title: 'RFC 4648：Base32 字母表',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        }
      ]
    },
    'zh-TW': {
      title: '2FA 金鑰在哪裡找',
      description:
        '2FA 金鑰是什麼、長什麼樣子？了解設定驗證應用程式時在哪裡找到金鑰、沒保存時如何重新取得，以及如何安全備份、為何不該隨意傳給他人。',
      sources: [
        {
          title: 'GitHub 文件：設定雙重驗證',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'GitHub 文件：變更雙重驗證方式',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-two-factor-authentication-delivery-methods-for-your-mobile-device'
        },
        {
          title: 'RFC 4648：Base32 字母表',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        }
      ]
    },
    ja: {
      title: '2FAシークレットキーの確認方法',
      description:
        '2段階認証のシークレットキーとは何か、設定時にどこで確認できるか、保存し忘れたときの再取得方法、安全な保管と共有の注意点を解説します。',
      sources: [
        {
          title: 'GitHub Docs：2要素認証を設定する',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'GitHub Docs：2要素認証の方法を変更する',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/changing-two-factor-authentication-delivery-methods-for-your-mobile-device'
        },
        {
          title: 'RFC 4648：Base32のアルファベット',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        }
      ]
    }
  },
  'batch-2fa-codes': {
    en: {
      title: 'Get 2FA codes in batches',
      description:
        'Paste up to 100 2FA secrets, spreadsheet rows or mixed text and get every current TOTP code at once in your browser, with safety tips for teams.',
      sources: [
        {
          title: '2fa.hot source code and feature overview',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        },
        {
          title: 'RFC 6238: the TOTP algorithm',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: 'MDN: URI fragments are not sent to the server',
          url: 'https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment'
        }
      ]
    },
    'zh-CN': {
      title: '批量获取 2FA 验证码',
      description:
        '一次粘贴最多 100 个 2FA 密钥、Excel 表格行或混合文本，在浏览器中批量获取当前 TOTP 验证码，并了解团队使用时的安全建议。',
      sources: [
        {
          title: '2fa.hot 源代码与功能介绍',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        },
        {
          title: 'RFC 6238：TOTP 算法说明',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: 'MDN：URI 片段不会发送到服务器',
          url: 'https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment'
        }
      ]
    },
    'zh-TW': {
      title: '批次取得 2FA 驗證碼',
      description:
        '一次貼上最多 100 組 2FA 金鑰、Excel 試算表的列或混合文字，在瀏覽器中批次取得目前的 TOTP 驗證碼，並了解團隊使用時的安全建議。',
      sources: [
        {
          title: '2fa.hot 原始碼與功能介紹',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        },
        {
          title: 'RFC 6238：TOTP 演算法說明',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: 'MDN：URI 片段不會傳送到伺服器',
          url: 'https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment'
        }
      ]
    },
    ja: {
      title: '2FAコードを一括生成',
      description:
        '最大100件の2FAシークレットやExcelの行、混在したテキストを貼り付けて、現在のTOTPコードをブラウザーで一括取得する方法と、チームで使うときの注意点を解説します。',
      sources: [
        {
          title: '2fa.hotのソースコードと機能概要',
          url: 'https://github.com/LZSMIAO/2FA.hot'
        },
        {
          title: 'RFC 6238：TOTPアルゴリズム',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        },
        {
          title: 'MDN：URIのフラグメントはサーバーに送信されない',
          url: 'https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment'
        }
      ]
    }
  },
  'otpauth-uri-format': {
    en: {
      title: 'The otpauth:// link format',
      description:
        'How the otpauth:// Key URI works: type, label, secret, issuer, algorithm, digits and period, what a 2FA QR code contains, and how to handle it safely.',
      sources: [
        {
          title: 'Google Authenticator wiki: Key Uri Format',
          url: 'https://github.com/google/google-authenticator/wiki/Key-Uri-Format'
        },
        {
          title: 'RFC 4648: Base32 encoding',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        },
        {
          title: 'RFC 6238: the TOTP algorithm',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        }
      ]
    },
    'zh-CN': {
      title: 'otpauth 链接格式详解',
      description:
        '了解 otpauth:// 链接的结构，secret、issuer、algorithm、digits、period 等参数的含义与默认值，以及 2FA 二维码的内容与安全处理。',
      sources: [
        {
          title: 'Google Authenticator wiki：Key Uri Format',
          url: 'https://github.com/google/google-authenticator/wiki/Key-Uri-Format'
        },
        {
          title: 'RFC 4648：Base32 编码',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        },
        {
          title: 'RFC 6238：TOTP 算法',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        }
      ]
    },
    'zh-TW': {
      title: 'otpauth 連結格式詳解',
      description:
        '了解 otpauth:// 連結的結構，secret、issuer、algorithm、digits、period 等參數的意義與預設值，以及 QR Code 的內容與安全處理。',
      sources: [
        {
          title: 'Google Authenticator wiki：Key Uri Format',
          url: 'https://github.com/google/google-authenticator/wiki/Key-Uri-Format'
        },
        {
          title: 'RFC 4648：Base32 編碼',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        },
        {
          title: 'RFC 6238：TOTP 演算法',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        }
      ]
    },
    ja: {
      title: 'otpauth URLの形式',
      description:
        'otpauth://リンクの構造、secret、issuer、algorithm、digits、periodの意味と既定値、2FAのQRコードの中身と安全な扱い方を解説します。',
      sources: [
        {
          title: 'Google Authenticator wiki：Key Uri Format',
          url: 'https://github.com/google/google-authenticator/wiki/Key-Uri-Format'
        },
        {
          title: 'RFC 4648：Base32エンコーディング',
          url: 'https://www.rfc-editor.org/rfc/rfc4648'
        },
        {
          title: 'RFC 6238：TOTPアルゴリズム',
          url: 'https://www.rfc-editor.org/rfc/rfc6238'
        }
      ]
    }
  },
  'enable-authenticator-app-2fa': {
    en: {
      title: 'Turn on authenticator app 2FA',
      description:
        'How to enable 2FA with an authenticator app: scan the QR code, save the setup key and backup codes, with notes for GitHub, Discord and X.',
      sources: [
        {
          title: 'GitHub Docs: Configuring two-factor authentication',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'Discord: Using an Authenticator App on Discord',
          url: 'https://support.discord.com/hc/en-us/articles/26304482627095-Using-an-Authenticator-App-on-Discord'
        },
        {
          title: 'X Help Center: How to use two-factor authentication',
          url: 'https://help.x.com/en/managing-your-account/two-factor-authentication'
        }
      ]
    },
    'zh-CN': {
      title: '如何开启验证器两步验证',
      description:
        '用验证器 App 开启两步验证：扫描二维码、确认验证码、保存设置密钥和备用码，并附 GitHub、Discord 和 X 的设置说明。',
      sources: [
        {
          title: 'GitHub 文档：配置双重身份验证',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'Discord：在 Discord 上使用验证器应用',
          url: 'https://support.discord.com/hc/en-us/articles/26304482627095-Using-an-Authenticator-App-on-Discord'
        },
        {
          title: 'X 帮助中心：如何使用双重验证',
          url: 'https://help.x.com/en/managing-your-account/two-factor-authentication'
        }
      ]
    },
    'zh-TW': {
      title: '如何設定驗證器雙重驗證',
      description:
        '用驗證器 App 設定雙重驗證：掃描 QR Code、輸入驗證碼、保存設定金鑰與備用碼，並附上 GitHub、Discord 和 X 的設定說明。',
      sources: [
        {
          title: 'GitHub 文件：設定雙重驗證',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'Discord：在 Discord 使用驗證器應用程式',
          url: 'https://support.discord.com/hc/en-us/articles/26304482627095-Using-an-Authenticator-App-on-Discord'
        },
        {
          title: 'X 說明中心：如何使用雙重驗證',
          url: 'https://help.x.com/en/managing-your-account/two-factor-authentication'
        }
      ]
    },
    ja: {
      title: '認証アプリで二段階認証を設定',
      description:
        '認証アプリで二段階認証を有効にする手順と、設定キーやバックアップコードの保管方法を解説。GitHub、Discord、Xの設定の要点も紹介します。',
      sources: [
        {
          title: 'GitHub Docs：2要素認証を設定する',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication'
        },
        {
          title: 'Discord：Discordで認証アプリを使う',
          url: 'https://support.discord.com/hc/en-us/articles/26304482627095-Using-an-Authenticator-App-on-Discord'
        },
        {
          title: 'Xヘルプセンター：2要素認証の使い方',
          url: 'https://help.x.com/en/managing-your-account/two-factor-authentication'
        }
      ]
    }
  },
  'lost-authenticator-recovery': {
    en: {
      title: 'Lost your 2FA phone?',
      description:
        'Lost the phone with your authenticator app? Look for a saved setup key, backup codes or another sign-in method, then use the service’s official recovery.',
      sources: [
        {
          title: 'Google: Fix common issues with 2-Step Verification',
          url: 'https://support.google.com/accounts/answer/185834?hl=en'
        },
        {
          title: 'Microsoft: Help with the Microsoft account recovery form',
          url: 'https://support.microsoft.com/en-us/account-billing/help-with-the-microsoft-account-recovery-form-b19c02d1-a782-dee6-93c3-dc8113b20c42'
        },
        {
          title: 'GitHub Docs: Recovering your account if you lose your 2FA credentials',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials'
        }
      ]
    },
    'zh-CN': {
      title: '2FA 手机丢了怎么办',
      description:
        '手机或验证器 App 丢了怎么办？先找设置密钥、备用码和其他已绑定的验证方式，再走原服务的官方账号恢复流程，恢复后重新绑定并做好备份。',
      sources: [
        {
          title: 'Google：解决两步验证的常见问题',
          url: 'https://support.google.com/accounts/answer/185834?hl=en'
        },
        {
          title: 'Microsoft：Microsoft 账户恢复表单帮助',
          url: 'https://support.microsoft.com/en-us/account-billing/help-with-the-microsoft-account-recovery-form-b19c02d1-a782-dee6-93c3-dc8113b20c42'
        },
        {
          title: 'GitHub 文档：丢失 2FA 凭据时如何恢复账号',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials'
        }
      ]
    },
    'zh-TW': {
      title: '2FA 手機遺失怎麼辦',
      description:
        '手機或驗證器 App 不見時，先找出設定金鑰、備用碼和其他已設定的驗證方式，再透過原服務的官方流程復原帳號，並在復原後重新設定。',
      sources: [
        {
          title: 'Google：解決兩步驟驗證的常見問題',
          url: 'https://support.google.com/accounts/answer/185834?hl=en'
        },
        {
          title: 'Microsoft：Microsoft 帳戶復原表單說明',
          url: 'https://support.microsoft.com/en-us/account-billing/help-with-the-microsoft-account-recovery-form-b19c02d1-a782-dee6-93c3-dc8113b20c42'
        },
        {
          title: 'GitHub 文件：遺失 2FA 憑證時如何復原帳號',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials'
        }
      ]
    },
    ja: {
      title: '2FAのスマホを紛失したら',
      description:
        'スマホ紛失や機種変更で認証アプリを引き継げなかったときは、設定キー、バックアップコード、他の認証方法を確認し、公式の復旧手続きを使います。',
      sources: [
        {
          title: 'Google：2段階認証プロセスに関する一般的な問題を解決する',
          url: 'https://support.google.com/accounts/answer/185834?hl=en'
        },
        {
          title: 'Microsoft：Microsoftアカウント回復フォームのヘルプ',
          url: 'https://support.microsoft.com/en-us/account-billing/help-with-the-microsoft-account-recovery-form-b19c02d1-a782-dee6-93c3-dc8113b20c42'
        },
        {
          title: 'GitHub Docs：2FA認証情報を失った場合のアカウント復旧',
          url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials'
        }
      ]
    }
  },
  'microsoft-authenticator-backup': {
    en: {
      title: 'Back up Microsoft Authenticator',
      description:
        'Back up Microsoft Authenticator on iPhone or Android, see why accounts cannot be exported to another app, and re-enroll 2FA while keeping each new setup key.',
      sources: [
        {
          title: 'Microsoft: Back up your accounts in Microsoft Authenticator',
          url: 'https://support.microsoft.com/en-us/authenticator/back-up-your-accounts-in-microsoft-authenticator'
        },
        {
          title: 'Microsoft: Restore account credentials from Microsoft Authenticator',
          url: 'https://support.microsoft.com/en-us/authenticator/restore-account-credentials-from-microsoft-authenticator'
        },
        {
          title: 'Microsoft: How to add your accounts to Microsoft Authenticator',
          url: 'https://support.microsoft.com/en-us/authenticator/how-to-add-your-accounts-to-microsoft-authenticator'
        }
      ]
    },
    'zh-CN': {
      title: 'Microsoft Authenticator 备份',
      description:
        'Microsoft Authenticator（微软身份验证器）如何在 iPhone 和安卓手机上备份、换手机后恢复，为什么不能导出到其他应用，以及怎样重新绑定并保存新密钥。',
      sources: [
        {
          title: '微软：在 Microsoft Authenticator 中备份账号',
          url: 'https://support.microsoft.com/en-us/authenticator/back-up-your-accounts-in-microsoft-authenticator'
        },
        {
          title: '微软：从 Microsoft Authenticator 恢复账号凭据',
          url: 'https://support.microsoft.com/en-us/authenticator/restore-account-credentials-from-microsoft-authenticator'
        },
        {
          title: '微软：如何将账号添加到 Microsoft Authenticator',
          url: 'https://support.microsoft.com/en-us/authenticator/how-to-add-your-accounts-to-microsoft-authenticator'
        }
      ]
    },
    'zh-TW': {
      title: 'Microsoft Authenticator 備份',
      description:
        'Microsoft Authenticator 如何在 iPhone、Android 上備份與換手機還原，為何無法匯出到其他 App，以及重新設定雙重驗證並保存新金鑰的方法。',
      sources: [
        {
          title: '微軟：在 Microsoft Authenticator 中備份帳號',
          url: 'https://support.microsoft.com/en-us/authenticator/back-up-your-accounts-in-microsoft-authenticator'
        },
        {
          title: '微軟：從 Microsoft Authenticator 還原帳號憑證',
          url: 'https://support.microsoft.com/en-us/authenticator/restore-account-credentials-from-microsoft-authenticator'
        },
        {
          title: '微軟：如何將帳號新增至 Microsoft Authenticator',
          url: 'https://support.microsoft.com/en-us/authenticator/how-to-add-your-accounts-to-microsoft-authenticator'
        }
      ]
    },
    ja: {
      title: 'Microsoft Authenticatorの移行',
      description:
        'Microsoft AuthenticatorのiPhone・Androidでのバックアップと機種変更時の復元、他アプリへ移せない理由、二段階認証の再設定方法を解説します。',
      sources: [
        {
          title: 'Microsoft：Microsoft Authenticatorでアカウントをバックアップする',
          url: 'https://support.microsoft.com/en-us/authenticator/back-up-your-accounts-in-microsoft-authenticator'
        },
        {
          title: 'Microsoft：Microsoft Authenticatorからアカウント資格情報を復元する',
          url: 'https://support.microsoft.com/en-us/authenticator/restore-account-credentials-from-microsoft-authenticator'
        },
        {
          title: 'Microsoft：Microsoft Authenticatorにアカウントを追加する方法',
          url: 'https://support.microsoft.com/en-us/authenticator/how-to-add-your-accounts-to-microsoft-authenticator'
        }
      ]
    }
  }
} as const
